vich_uploader:
    db_driver: orm

    mappings:
        articles_front:
            uri_prefix: /images/articles_front
            upload_destination: '%kernel.project_dir%/public/images/articles_front'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true